2022-01-08 16:47:27,764 ERROR: Exception on /edit_profile [GET] [in /Users/s.selle/code/flaskblog/venv/lib/python3.8/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/s.selle/code/flaskblog/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/s.selle/code/flaskblog/venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/s.selle/code/flaskblog/venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/s.selle/code/flaskblog/venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/s.selle/code/flaskblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/s.selle/code/flaskblog/app/routes.py", line 86, in edit_profile
    form = EditProfileForm(current_user.username)
  File "/Users/s.selle/code/flaskblog/venv/lib/python3.8/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'original_username'
2022-01-08 16:47:32,963 INFO: Microblog startup [in /Users/s.selle/code/flaskblog/app/__init__.py:32]
2022-01-15 15:48:39,049 INFO: Microblog startup [in /Users/s.selle/code/flaskblog/app/__init__.py:32]
